myexe:  myMain1.o myMathFunc.o mystrFunc.o
	gcc -o myexe myMain1.o myMathFunc.o mystrFunc.o
myMathFunc.o: myMathFunc.c
	gcc -c myMathFunc.c
mystrFunc.o: mystrFunc.c
	gcc -c mystrFunc.c
myMain1.o: myMain1.c
	gcc -c myMain1.c
